name: Sync Calendar with Daily Notes

on:
  # Run every 4 hours
  schedule:
    - cron: "0 */4 * * *"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install requests recurring-ical-events icalendar

      - name: Run the calendar sync script
        env:
          GOOGLE_CALENDAR_DANIEL_PERSONAL: ${{ secrets.GOOGLE_CALENDAR_DANIEL_PERSONAL }}
          GOOGLE_CALENDAR_DANIEL_EVENTS: ${{ secrets.GOOGLE_CALENDAR_DANIEL_EVENTS }}
          GOOGLE_CALENDAR_HOLIDAYS_US: ${{ secrets.GOOGLE_CALENDAR_HOLIDAYS_US }}
        run: |
          echo "Starting calendar sync at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          python .scripts/update_calendar.py
          echo "Finished calendar sync at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
      - name: Commit and push with retry
        run: |
          # Fetch the latest changes
          git fetch origin main
          
          # Stage changes
          git add .
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "BOT: update daily notes with Google Calendar events [$(date -u '+%Y-%m-%d %H:%M:%S UTC')]"
          
          # Retry loop for push attempts
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Push attempt $attempt of $max_attempts"
            
            # Fetch and rebase before each attempt
            git fetch origin main
            git rebase origin/main
            
            if git push origin main; then
              echo "Push successful"
              exit 0
            fi
            
            attempt=$((attempt + 1))
            if [ $attempt -le $max_attempts ]; then
              echo "Push failed, retrying in 10 seconds..."
              sleep 10
            fi
          done
          
          echo "Failed to push after $max_attempts attempts"
          exit 1
